# Generated by Django 2.1.7 on 2019-05-17 01:08

import DjangoUeditor.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Django_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '笔记', 'verbose_name_plural': '笔记'},
        ),
        migrations.AddField(
            model_name='article',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 17, 1, 8, 15, 426162, tzinfo=utc), verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='article',
            name='modify_time',
            field=models.DateTimeField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AddField(
            model_name='article',
            name='text',
            field=DjangoUeditor.models.UEditorField(blank=True, verbose_name='内容\t'),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.CharField(max_length=200, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=200, verbose_name='标题'),
        ),
    ]
