# Generated by Django 2.1.7 on 2019-05-17 02:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Django_web', '0002_auto_20190517_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 17, 2, 57, 30, 347416, tzinfo=utc), verbose_name='创建时间'),
        ),
    ]
