# Generated by Django 2.1.7 on 2019-05-17 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Django_web', '0003_auto_20190517_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='add_time',
        ),
    ]
