# Generated by Django 2.1.7 on 2019-05-22 16:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Django_web', '0005_article_add_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 22, 16, 18, 12, 858727, tzinfo=utc), verbose_name='创建时间'),
        ),
    ]
