# Generated by Django 2.1.8 on 2019-06-15 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Django_web', '0007_auto_20190615_2047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '分类', 'verbose_name_plural': '分类'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '标签', 'verbose_name_plural': '标签'},
        ),
    ]
